environment_variables: {}
external_package_dirs: []
weights:
  - source: "hf://tiiuae/falcon-7b@main"
    mount_location: "/models/falcon-7b"
    allow_patterns:
      - "*.bin"
    ignore_patterns:
      - "coreml/*"
  - source: "hf://tiiuae/falcon-7b-instruct@main"
    mount_location: "/models/falcon-7b-instruct"
    allow_patterns:
      - "*.bin"
    ignore_patterns:
      - "coreml/*"
model_name: Binoculars
python_version: py311
requirements:
- git+https://github.com/ahans30/Binoculars.git
resources:
  accelerator: A10G:2
secrets: {}
system_packages: []
