model_name: Palmyra x5.5 H200 BIS 6
python_version: py39
resources:
  accelerator: H200:8
  cpu: "1"
  memory: 10Gi
  use_gpu: true
model_metadata:
  example_model_input:
    {
      "model": "Writer/Palmyra_x5.5",
      "messages":
        [
          {
            "role": "user",
            "content": "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order. class Solution: def twoSum(self, nums: List[int], target: int) -> List[int]:",
          },
        ],
      "stream": true,
      "max_tokens": 2048,
      "temperature": 0.5,
    }
weights:
  - source: "hf://Writer/Palmyra_x5.5@main"
    auth_secret_name: "hf_access_token"
    mount_location: "/app/models/palmyra"
    ignore_patterns: ["*.md", "*.txt"]
trt_llm:
  build:
    checkpoint_repository:
      repo: michaelfeil/empty-model
      revision: main
      source: HF
  inference_stack: v2
  runtime:
    enable_chunked_prefill: true
    max_batch_size: 32
    max_num_tokens: 8192
    max_seq_len: 202752
    tensor_parallel_size: 8
    served_model_name: Writer/Palmyra_x5.5
    patch_kwargs:
      guided_decoding_backend: "xgrammar"
      moe_expert_parallel_size: 8
      kv_cache_config:
        free_gpu_memory_fraction: 0.8
        enable_block_reuse: true
        event_buffer_max_size: 16384
        host_cache_size: 100000000000
      cuda_graph_config:
        enable_padding: false
      enable_iter_perf_stats: true
      tool_call_parser: glm47
      reasoning_parser: glm47
      router_mode: kv
      opt_num_tokens: null
      tokenizer_limit_length: 202752
      moe_config:
        backend: CUTLASS
      model_level_stop_words:
        - "<|user|>"
        - "<|observation|>"
      model_path: /app/models/palmyra
