// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: spacer.proto

package yapper

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	YapperService_Yap_FullMethodName = "/yapper.YapperService/Yap"
)

// YapperServiceClient is the client API for YapperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YapperServiceClient interface {
	Yap(ctx context.Context, in *YapRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[YapReply], error)
}

type yapperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewYapperServiceClient(cc grpc.ClientConnInterface) YapperServiceClient {
	return &yapperServiceClient{cc}
}

func (c *yapperServiceClient) Yap(ctx context.Context, in *YapRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[YapReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &YapperService_ServiceDesc.Streams[0], YapperService_Yap_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[YapRequest, YapReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type YapperService_YapClient = grpc.ServerStreamingClient[YapReply]

// YapperServiceServer is the server API for YapperService service.
// All implementations must embed UnimplementedYapperServiceServer
// for forward compatibility.
type YapperServiceServer interface {
	Yap(*YapRequest, grpc.ServerStreamingServer[YapReply]) error
	mustEmbedUnimplementedYapperServiceServer()
}

// UnimplementedYapperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedYapperServiceServer struct{}

func (UnimplementedYapperServiceServer) Yap(*YapRequest, grpc.ServerStreamingServer[YapReply]) error {
	return status.Errorf(codes.Unimplemented, "method Yap not implemented")
}
func (UnimplementedYapperServiceServer) mustEmbedUnimplementedYapperServiceServer() {}
func (UnimplementedYapperServiceServer) testEmbeddedByValue()                       {}

// UnsafeYapperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YapperServiceServer will
// result in compilation errors.
type UnsafeYapperServiceServer interface {
	mustEmbedUnimplementedYapperServiceServer()
}

func RegisterYapperServiceServer(s grpc.ServiceRegistrar, srv YapperServiceServer) {
	// If the following call pancis, it indicates UnimplementedYapperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&YapperService_ServiceDesc, srv)
}

func _YapperService_Yap_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(YapRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(YapperServiceServer).Yap(m, &grpc.GenericServerStream[YapRequest, YapReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type YapperService_YapServer = grpc.ServerStreamingServer[YapReply]

// YapperService_ServiceDesc is the grpc.ServiceDesc for YapperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YapperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yapper.YapperService",
	HandlerType: (*YapperServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Yap",
			Handler:       _YapperService_Yap_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "spacer.proto",
}
