model_name: Hello Model Cache GCS
python_version: py311
requirements: [""]
resources:
  accelerator: null
  cpu: "1"
  memory: 2Gi
  use_gpu: false
build:
  secret_to_path_mapping:
    gcs-service-account-jsn: /secrets/gcs-service-account-jsn
secrets: { gcs-service-account-jsn: null } # null is encouraged, as this will automatically use the one provided by baseten.co
weights:
  - source: "gs://llama-3-2-1b-instruct/"
    mount_location: "/weights/llama"
    auth_secret_name: "gcs-service-account-jsn"
