model_name: MetaVoice 1B
description: MetaVoice is a transformer-based model for TTS
environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input: '"text to speech models are cool"'
python_version: py311
data_dir: data
weights:
  - source: "hf://metavoiceio/metavoice-1B-v0.1@main"
    mount_location: "/models/metavoice-1B-v0.1"
    allow_patterns:
      - "*.pt"
  - source: "hf://facebook/multiband-diffusion@main"
    mount_location: "/models/multiband-diffusion"
    allow_patterns:
      - "mbd_comp_8.pt"
  - source: "hf://facebook/encodec_24khz@main"
    mount_location: "/models/encodec_24khz"
    allow_patterns:
      - "*.safetensors"
requirements_file: ./requirements.txt
resources:
  accelerator: "A10G"
  use_gpu: true
secrets:
  hf_access_token: "ENTER HF ACCESS TOKEN HERE"
system_packages:
- ffmpeg
