# # Setting up the config.yaml
#
# The `config.yaml` file is where you need to include the changes to
# actually cache the weights at build time.
environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input: { "prompt": "What is the meaning of life?" }
model_name: Llama with Cached Weights
python_version: py39
requirements:
  - accelerate==0.21.0
  - safetensors==0.3.2
  - torch==2.0.1
  - transformers==4.34.0
  - sentencepiece==0.1.99
  - numpy==1.26.4
# # Configuring the weights
#
# To cache model weights, set the `weights` key.
# The `source` field allows you to specify a Hugging Face
# repo to mount with BDN, and the `ignore_patterns` field allows you
# to specify files to ignore.
#
# Check out the [guide](https://truss.baseten.co/guides/model-cache) for more info.
weights:
  - source: "hf://NousResearch/Llama-2-7b-chat-hf@main"
    mount_location: "/weights/llama-2-7b-chat-hf"
    ignore_patterns:
      - "*.bin"
resources:
  cpu: "4"
  memory: 30Gi
  use_gpu: True
  accelerator: A10G
secrets: {}
# # Deploy the model
#
# Deploy the model like you would other Trusses, with:
# ```bash
# $ truss push
# ```
#  <Note>
#  The build step will take  longer than with the normal
#  Llama Truss, since bundling the model weights is now happening during the build.
#  The deploy step & scale-ups will happen much faster with this approach.
#  </Note>
#
# You can then invoke the model with:
# ```bash
# $ truss predict -d '{"inputs": "What is a large language model?"}'
# ```
