model_name: "model:llama-3.3-70b-instruct preset:latency"

model_metadata:
  tags:
    - openai-compatible
  example_model_input:
    stream: true
    model: nvidia/Llama-3.3-70B-Instruct-FP8
    messages:
      - role: user
        content: Tell me everything you know about optimized inference.
    max_tokens: 512
    temperature: 0.5

python_version: py313

secrets:
  hf_access_token: null

weights:
  - source: hf://nvidia/Llama-3.3-70B-Instruct-FP8@main
    allow_patterns:
      - "*.safetensors"
      - "*.json"
      - "*.model"
      - tokenizer.model
      - "*.tiktoken"
      - "*.jinja"
    mount_location: /app/model_cache/llama-3-3-70b-instruct
    ignore_patterns:
      - original/*
      - "*.pth"
    auth_secret_name: hf_access_token

resources:
  cpu: "4"
  memory: 40Gi
  use_gpu: true
  accelerator: H100:4

data_dir: data

runtime:
  predict_concurrency: 128
  streaming_read_timeout: 60

trt_llm:
  build:
    checkpoint_repository:
      repo: michaelfeil/empty-model
      source: HF
      revision: main
      runtime_secret_name: hf_access_token
  runtime:
    max_seq_len: 131072
    patch_kwargs:
      model_path: /app/model_cache/llama-3-3-70b-instruct
      model_path_for_tokenizer: /app/model_cache/llama-3-3-70b-instruct
      cuda_graph_config:
        enable_padding: true
        max_batch_size: 128
    max_batch_size: 128
    max_num_tokens: 8192
    served_model_name: nvidia/Llama-3.3-70B-Instruct-FP8
    tensor_parallel_size: 4
    enable_chunked_prefill: true
  inference_stack: v2
  version_overrides:
    v2_llm_version: null
