build:
  arguments:
    endpoint: Completions
    model: tiiuae/falcon-7b
  model_server: VLLM
environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: Falcon 7B vLLM
python_version: py311
requirements: []
resources:
  accelerator: A10G
  cpu: 2500m
  memory: 15Gi
  use_gpu: true
secrets: {}
system_packages: []
